name: React build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code.
    - uses: actions/checkout@main
    
    - run: npm install
    - run: npm run build
