name: React build

on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  checks: write

env:
  AWS_REGION: "ap-northeast-2"
  ECR_REPOSITORY: "blocko-devops-test"
  ECS_SERVICE: "blocko-devops-test-app"
  ECS_CLUSTER: "blocko-devops-test-cluster"
  ECS_TASK_DEFINITION: .aws/definition/blocko-devops-register-task-definition-revision1.json
  CONTAINER_NAME: "blocko-devops-test"
  IMAGE_TAG: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node modules, run ci
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
          run: npm ci

      - name: Lint Check
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

      - name: Test
        run: npm run test

      - name: React Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY_PUBLIC: "public.ecr.aws/x3j1o7j5"
          # IMAGE_TAG: "1.0"
        run: |
          echo ${{ github.ref }}
          ref='refs/tags/v'
          if [[ ${{ github.ref }} == *${ref}* ]]; then
          v= $(echo ${{ github.ref }} | cut -d '/' -f3)
          echo "version tag is ${v}"
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x3j1o7j5
          docker build -t $ECR_REGISTRY_PUBLIC/${{ env.ECR_REPOSITORY }}:${v} .
          docker push $ECR_REGISTRY_PUBLIC/${{ env.ECR_REPOSITORY }}:${v}
          echo "image=$ECR_REGISTRY_PUBLIC/${{ env.ECR_REPOSITORY }}:${v}" >> $GITHUB_OUTPUT
          else
          docker build -t $ECR_REGISTRY_PUBLIC/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
